// flow-typed signature: fadb1dc6044dd9af4a9ee4e98eb62323
// flow-typed version: <<STUB>>/javascript-csv_v^1.0.7/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-csv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-csv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'javascript-csv/examples/node-usage' {
  declare module.exports: any;
}

declare module 'javascript-csv/src/jquery.csv' {
  declare module.exports: any;
}

declare module 'javascript-csv/test/fixtures' {
  declare module.exports: any;
}

declare module 'javascript-csv/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'javascript-csv/examples/node-usage.js' {
  declare module.exports: $Exports<'javascript-csv/examples/node-usage'>;
}
declare module 'javascript-csv/src/jquery.csv.js' {
  declare module.exports: $Exports<'javascript-csv/src/jquery.csv'>;
}
declare module 'javascript-csv/test/fixtures.js' {
  declare module.exports: $Exports<'javascript-csv/test/fixtures'>;
}
declare module 'javascript-csv/test/test.js' {
  declare module.exports: $Exports<'javascript-csv/test/test'>;
}
