// flow-typed signature: 82e98aa86e01623cf03242fdd973cf48
// flow-typed version: <<STUB>>/standardx_v^5.0.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standardx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standardx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standardx/bin/cmd' {
  declare module.exports: any;
}

declare module 'standardx/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standardx/bin/cmd.js' {
  declare module.exports: $Exports<'standardx/bin/cmd'>;
}
declare module 'standardx/index' {
  declare module.exports: $Exports<'standardx'>;
}
declare module 'standardx/index.js' {
  declare module.exports: $Exports<'standardx'>;
}
declare module 'standardx/options.js' {
  declare module.exports: $Exports<'standardx/options'>;
}
